### ISSUE TITLE
Previous versions of data?

### ISSUE THREAD

**Issue by sgfin** [Orphanet/Orphadata.org#4]
Hello!

I can see through the github history that it is possible to access versions of the xml files going back to June 2017, but I also see that orphanet has existed going back to at least 2007.  Is it possible to access pre-2017 versions of your data files?  If so, where are they available?

Thank you,
Sam

**Comment by Orphanet** [comment]
Dear Samuel,

There is no other source but we do have dates of creation and dates of update of data in our database, however we do emit . We have already provided this data after signature of a data transfer agreement. If that interests you let me know the name and position of the legal representative of your institution as well as the postal address and I will send a draft for review.

Best,

Charlotte
